### ISSUE TITLE
it  might  reduce  code readability  when  tag  is  so  long

### ISSUE THREAD

**Issue by tylitianrui** [bytedance/go-tagexpr#10]
it is  so powerful.👍
it  might  reduce  code readability  when  tag  is  so  long. 
how to   express  ` switch - case `  case

**Comment by henrylee2cn** [comment]
Too long code, including switch, can be solved with registered functions: https://github.com/bytedance/go-tagexpr/blob/master/spec_func.go#L36

**Comment by tylitianrui** [comment]
thx
