### ISSUE TITLE
校验Header时没有做归一化

### ISSUE THREAD

**Issue by Duslia997** [bytedance/go-tagexpr#22]
header在业务上有归一化的逻辑，但是在库里没有做归一化，这里希望能支持下。

**Comment by henrylee2cn** [comment]
什么是归一化？

**Comment by Duslia997** [comment]
比如user_name -> User_name，user-name -> User-Name。因为对大小心不敏感，所以业务上处理之前先做了归一化处理

**Comment by Duslia997** [comment]
要不lark聊一下😂  yinxuran
