### ISSUE TITLE
在 vd 的时候 msg 里如果包含单引号会产生不可预料的错误

### ISSUE THREAD

**Issue by zhaobenx** [bytedance/go-tagexpr#28]
如在
```
`query:"profiling_id" vd:"@:len($)==32; msg:'profiling_id's length is invalid'"`
```
这样的句子里，msg 里包含的单引号会使整个vd失效而无法产生正确结果； 如果将msg 里的单引号转义 \'，会产生一个更奇葩的效果就是服务第一次的验证会成功，而之后的验证都会失效。
以及同学有没有内部的联系方式方便讨论呀？

**Comment by henrylee2cn** [comment]
@zhaobenx 单引号是msg的分隔符，内部单引号确实应该转义。你可以lark联系我 liyachuan

**Comment by henrylee2cn** [comment]
使用 双斜杠 转义 单引号 可以解决（单引号转义是非法字符）：
`query:"profiling_id" vd:"@:len($)==32; msg:'profiling_id\\'s length is invalid'"`
