### ISSUE TITLE
../github.com/bytedance/go-tagexpr/tagexpr.go:622:14: v.MapRange undefined (type reflect.Value has no field or method MapRange)

### ISSUE THREAD

**Issue by Mjiulee** [bytedance/go-tagexpr#4]
../github.com/bytedance/go-tagexpr/tagexpr.go:622:14: v.MapRange undefined (type reflect.Value has no field or method MapRange)

**Comment by henrylee2cn** [comment]
go version >= 1.12

**Comment by henrylee2cn** [comment]
Compatible with go version 1.9

https://github.com/bytedance/go-tagexpr/commit/3fa82cc32f9923f55f2abb457f6fccd1e1386b9f
