### ISSUE TITLE
直接改开源包的配置不太好吧，被坑了

### ISSUE THREAD

**Issue by geebos** [bytedance/go-tagexpr#62]
https://github.com/bytedance/go-tagexpr/blob/a44f579c38661a554dd0264d5a9aefed6f735204/binding/gjson/gjson.go#L47

**Comment by andeya** [comment]
嗯，确实考虑不周，会影响gjson在其他模块的使用，我们把它移入vendor吧

**Comment by andeya** [comment]
[v2.9.8](https://github.com/bytedance/go-tagexpr/releases/tag/v2.9.8)
