### ISSUE TITLE
go mod 问题

### ISSUE THREAD

**Issue by alpha-baby** [bytedance/go-tagexpr#8]
我把demo copy到本地尝试运行，但是因为go mod 下载包的原因而不不能通过编译，

> 我用的是go 12.4 
GO111MODULE=on
GOPROXY=https://athens.azurefd.net 

tagexpr 使用了包 `github.com/henrylee2cn/goutil/tpack`
这个包用 go mod tidy 下载不下来

**Comment by alpha-baby** [comment]
https://github.com/henrylee2cn/goutil/issues/6

**Comment by henrylee2cn** [comment]
Already fixed https://github.com/henrylee2cn/goutil/commit/55957c7df7ac0868f220144e37966ab331ecfe26
